version: '3.8'

services:
  jekyll:
    build: docs
    command: jekyll serve --watch --drafts --future --host 0.0.0.0
    ports:
      - "4000:4000"
    volumes:
      - ./docs:/srv/jekyll
    working_dir: /srv/jekyll
