name: Build & Deploy Jekyll with Custom Plugins

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Ruby／Bundler のセットアップ（キャッシュは手動で制御）
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.3'

      # docs 以下の vendor/bundle をキャッシュ
      - name: Cache Ruby gems
        uses: actions/cache@v4
        with:
          path: docs/vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('docs/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install gems
        working-directory: docs
        run: |
          # vendor/bundle にインストールする設定
          bundle config set path 'vendor/bundle'
          # 並列ジョブ数4、リトライ3回
          bundle install --jobs 4 --retry 3

      - name: Build site
        working-directory: docs
        run: bundle exec jekyll build --destination ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - id: deploy
        uses: actions/deploy-pages@v4
